services:
  apbs-time-app.client.auth:
    container_name: time.app.auth
    image: ${DOCKER_REGISTRY-}apbstimeappclientauth
    build:
      context: .
      dockerfile: apbs-time-app/Dockerfile
    depends_on:
        - postgres
        - apbs-time-app.client.timemanager
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DefaultConnection=Server=sqlserver;Database=mtaDb;User=sa;Password=sa12345@;TrustServerCertificate=True;Authentication=SqlPassword;
 
  apbs-time-app.client.timemanager:
    image: ${DOCKER_REGISTRY-}apbstimeappclienttimemanager
    build:
      context: .
      dockerfile: Apbs-Time-App.Client.TimeManager/Dockerfile
    depends_on:
        - apbs-time-app-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  apbs-time-app.client.gateway:
    container_name: time.app.gateway
    image: ${DOCKER_REGISTRY-}apbstimeappclientgateway
    build:
      context: .
      dockerfile: time-app-gateway/Dockerfile
    ports:
        - 58167:8080
        - 58168:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
 
  apbs-time-app-admin:
    container_name: time-app-admin
    image: ${DOCKER_REGISTRY-}apbstimeappadmin
    build:
      context: .
      dockerfile: apbs-time-app-admin/Dockerfile
    ports:
        - 58169:8080
        - 58170:8081
    depends_on:
        - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DefaultConnection=Server=sqlserver;Database=TenantDB;User=sa;Password=sa12345@;TrustServerCertificate=True;Authentication=SqlPassword;
  
  # sqlserver:
  #     image: mcr.microsoft.com/mssql/server:2022-latest
  #     container_name: sqlserver
  #     environment:
  #       ACCEPT_EULA: "Y"
  #       MSSQL_SA_PASSWORD: "sa12345@"
  #     ports:
  #       - "9632:1433"
  #     volumes:
  #       - sqlserverdata:/var/opt/mssql
   
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_DB: time
      POSTGRES_USER: yk
      POSTGRES_PASSWORD: yk12345@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10 
    volumes:
      - pgdata:/var/lib/postgresql/data 

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI


volumes:
  pgdata:


